version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ./src/:/docker-entrypoint-initdb.d/
